"""Write CASE_STUDY.md: the Navy Federal read-out, generated from the data.

Every number comes from the processed Call Report panel, the peer set, the
forecast and (when present) the industry backtest, so the document can be
regenerated after each NCUA release and never drifts from the app.

Run from api/:  .venv/bin/python -m pipeline.case_study
"""

import json
from pathlib import Path

import numpy as np
import pandas as pd

from pipeline.forecast import forecast_cu
from pipeline.metrics import derive, peer_stats

ROOT = Path(__file__).resolve().parents[1]
PANEL = ROOT / "data" / "processed" / "call_reports.csv.gz"
BACKTEST = ROOT / "data" / "processed" / "backtest_summary.json"
OUT = ROOT.parent / "CASE_STUDY.md"
CU = 5536
WELL = 0.07
SEVERE = {"nco": 0.012, "roa": -0.003, "growth": 0.06}  # matches web/src/lib/analysis.js (history-calibrated)


def pct(v, d=2):
    return f"{v * 100:.{d}f}%"


def usd(v):
    for div, unit in ((1e12, "T"), (1e9, "B"), (1e6, "M")):
        if abs(v) >= div:
            return f"${v / div:.1f}{unit}"
    return f"${v:,.0f}"


def quarter(q):
    return f"{q[4:]} {q[:4]}"


def ordinal(n):
    n = int(round(n))
    suffix = "th" if 10 <= n % 100 <= 20 else {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")
    return f"{n}{suffix}"


def project(base, growth, extra_nco, roa_shift):
    """Four-quarter capital roll-forward; mirrors projectCapital in the web app."""
    assets, nw = base["assets"], base["net_worth"]
    for _ in range(4):
        nw += assets * (base["roa"] + roa_shift) / 4 - assets * base["loan_share"] * extra_nco / 4
        assets *= 1 + growth / 4
    return nw / assets


def breakeven(base, growth, roa_shift):
    assets, earn, loans = base["assets"], 0.0, 0.0
    for _ in range(4):
        earn += assets * (base["roa"] + roa_shift) / 4
        loans += assets * base["loan_share"] / 4
        assets *= 1 + growth / 4
    return (base["net_worth"] + earn - WELL * assets) / loans


def main():
    df = derive(pd.read_csv(PANEL))
    rows = df[df.cu_number == CU].sort_values("quarter")
    now = rows.iloc[-1]
    peers = peer_stats(df, CU)
    last = lambda k: peers["series"][k][-1]
    fc = forecast_cu(rows)
    industry_assets = df[df.quarter == df.quarter.max()].total_assets.sum()

    nco, dq, roa, nwr = (last(k) for k in ("net_charge_off_rate", "delinquency_rate", "roa", "net_worth_ratio"))
    group = sorted([m["net_charge_off_rate"] for m in peers["members"] if m["net_charge_off_rate"] is not None]
                   + [now.net_charge_off_rate], reverse=True)
    rank = group.index(now.net_charge_off_rate) + 1
    pre = rows.set_index("quarter").loc["2021Q4"]
    after = rows[rows.quarter > "2021Q4"]
    peak = after.loc[after.net_charge_off_rate.idxmax()]
    peer_2021 = next(p["median"] for p in peers["series"]["net_charge_off_rate"] if p["quarter"] == "2021Q4")

    assets_path = fc["series"]["total_assets"]["path"]
    base = {"assets": now.total_assets, "net_worth": now.net_worth_ratio * now.total_assets,
            "loan_share": now.total_loans / now.total_assets, "roa": now.roa, "nco": now.net_charge_off_rate}
    growth = assets_path[-1]["point"] / now.total_assets - 1
    calm = project(base, growth, 0, 0)
    calm_be = breakeven(base, growth, 0)
    severe = project(base, growth + SEVERE["growth"], SEVERE["nco"], SEVERE["roa"])
    severe_be = breakeven(base, growth + SEVERE["growth"], SEVERE["roa"])
    end_q = assets_path[-1]["quarter"]

    loans = fc["series"]["total_loans"]
    loans_end = loans["path"][-1]
    nw_end = fc["series"]["net_worth_ratio"]["path"][-1]
    chosen = loans["backtest"][loans["model"]]
    bt = json.loads(BACKTEST.read_text()) if BACKTEST.exists() else None

    # Reconcile the earnings-retention case with the statistical forecast from the history itself.
    years = (len(rows) - 1) / 4
    hist_growth = (now.total_assets / rows.total_assets.iloc[0]) ** (1 / years) - 1
    hist_roa = rows[rows.quarter.str.endswith("Q4")].roa.mean()
    nwr_avg = rows.net_worth_ratio.mean()
    capital_growth = hist_roa / nwr_avg
    pace = ("earnings roughly kept pace with growth" if abs(capital_growth - hist_growth) < 0.02 else
            "earnings outpaced growth" if capital_growth > hist_growth else "growth outpaced earnings")

    high_loss = now.net_charge_off_rate > nco["median"] * 1.5
    strong = roa["percentile"] >= 50
    title = ("Navy Federal: losses run high, and earnings carry them" if high_loss and strong else
             "Navy Federal: losses run high, and earnings are not keeping pace" if high_loss else
             "Navy Federal: a read-out from the filings")
    lines = [
        f"# {title}",
        "",
        f"*A read-out of Navy Federal Credit Union (charter {CU}) from its NCUA 5300 Call Report filings, "
        f"{quarter(df.quarter.min())} to {quarter(now.quarter)}. Generated by `python -m pipeline.case_study`; "
        f"the live version is the Case study page in CU Pulse.*",
        "",
        "## The question",
        "",
        f"Navy Federal holds {usd(now.total_assets)} of assets, {pct(now.total_assets / industry_assets, 1)} of the "
        f"credit union industry, and serves {now.members / 1e6:.1f} million members. Its net charge-off rate is "
        f"**{pct(now.net_charge_off_rate)}** annualized, {now.net_charge_off_rate / nco['median']:.1f}× the median of its "
        f"{peers['peer_count']} size peers ({pct(nco['median'])}) and "
        f"{'the highest in the group' if rank == 1 else ordinal(rank) + ' highest in the group'}. Is that a capital problem?",
        "",
        f"**Short answer: not at present.** Earnings absorb the losses, and capital stays above NCUA's 7% "
        f"well-capitalized line even under a severe scenario." if severe >= WELL else
        f"**Short answer: it could become one.** Under the severe scenario, capital falls below the 7% line within four quarters.",
        "",
        "| | Navy Federal | Peer median | Percentile |",
        "|---|---:|---:|---:|",
        f"| Net charge-off rate | {pct(now.net_charge_off_rate)} | {pct(nco['median'])} | {ordinal(nco['percentile'])} |",
        f"| Delinquency, 60+ days | {pct(now.delinquency_rate)} | {pct(dq['median'])} | {ordinal(dq['percentile'])} |",
        f"| Return on assets | {pct(now.roa)} | {pct(roa['median'])} | {ordinal(roa['percentile'])} |",
        f"| Net worth ratio (as reported) | {pct(now.net_worth_ratio)} | {pct(nwr['median'])} | {ordinal(nwr['percentile'])} |",
        "",
        f"Peers: {peers['method']}.",
        "",
        "## What the filings show",
        "",
        f"- Losses went from {pct(pre.net_charge_off_rate)} at the end of 2021 to a high of "
        f"{pct(peak.net_charge_off_rate)} in {quarter(peak.quarter)}, and sit at {pct(now.net_charge_off_rate)} now. "
        f"Over the same years the peer median went from {pct(peer_2021)} to {pct(nco['median'])}.",
        f"- Delinquency points the same way: {pct(now.delinquency_rate)} of loans are 60+ days past due against a peer "
        f"median of {pct(dq['median'])}.",
        f"- Return on assets is {pct(now.roa)}, the {ordinal(roa['percentile'])} percentile of peers: the loan book earns "
        f"more than enough to cover what it loses.",
        f"- The net worth ratio is {pct(now.net_worth_ratio)}, about {usd((now.net_worth_ratio - WELL) * now.total_assets)} "
        f"above the 7% line.",
        "",
        "## How much loss it could absorb",
        "",
        "Capital rolled forward four quarters: pre-loss earnings less any charge-offs above today's rate, with assets "
        "growing at the model's projected pace. Credit unions pay no income tax, so losses pass straight to net worth.",
        "",
        f"| Scenario | Net worth ratio at {quarter(end_q)} | Extra charge-offs before 7% |",
        "|---|---:|---:|",
        f"| Reported, {quarter(now.quarter)} | {pct(now.net_worth_ratio)} | |",
        f"| Earnings retention: no shock, all of today's {pct(now.roa)} ROA kept, assets +{pct(growth, 1)} | {pct(calm)} | +{pct(calm_be, 1)} ({pct(base['nco'] + calm_be, 1)} all-in) |",
        f"| Severe (95th-percentile charge-off rise, 2018–2026): charge-offs +1.2 pts, pre-loss ROA −0.3 pts, assets +6 pts faster | {pct(severe)} | +{pct(severe_be, 1)} |",
        f"| Statistical forecast ({fc['series']['net_worth_ratio']['model_label']}) | {pct(nw_end['point'])} | |",
        "",
        "## What the forecast says, and how far to trust it",
        "",
        f"Loans are projected at {usd(loans_end['point'])} by {quarter(loans_end['quarter'])} (80% range "
        f"{usd(loans_end['lo80'])}–{usd(loans_end['hi80'])}); the net worth ratio at {pct(nw_end['point'])}. In Navy "
        f"Federal's own backtest the selected loans model ({loans['model_label']}) had {pct(chosen['error'], 1)} mean "
        f"absolute percentage error, and its 80% ranges held {pct(chosen['coverage80'], 0)} of outcomes: useful for "
        f"direction, too confident on range.",
        "",
        f"**Why the forecast ({pct(nw_end['point'])}) sits below the earnings-retention case ({pct(calm)}).** They answer "
        f"different questions. The retention case applies today's {pct(now.roa)} ROA to assets growing {pct(growth, 1)} a "
        f"year. The forecast extrapolates the ratio's own history, in which assets grew about {pct(hist_growth, 1)} a year "
        f"against an average year-end ROA of {pct(hist_roa)}; {pace}, and the ratio stayed between "
        f"{pct(rows.net_worth_ratio.min())} and {pct(rows.net_worth_ratio.max())}. Dividends on shares are already an "
        f"expense before net income, so they are not the gap.",
    ]
    if bt and bt["overall"].get("total_loans"):
        b = bt["overall"]["total_loans"]
        lines += [
            "",
            f"Across all {bt['credit_unions']:,} active credit unions, choosing the model on early quarters and scoring it "
            f"on later ones it never saw, the loans forecast cut median error by {pct(b['skill_vs_drift'], 0)} against a "
            f"random walk with drift ({pct(b['median_error'])} vs {pct(b['median_drift_error'])}), beating it for "
            f"{pct(b['beats_drift_share'], 0)} of credit unions, and its 80% ranges held {pct(b['coverage80_mean'], 0)} "
            f"of outcomes.",
        ]
    lines += [
        "",
        "## What I would look at next",
        "",
        "- **Loan mix.** The Call Report breaks loans out by product (credit card, auto, real estate); charge-offs by product would show where the losses sit.",
        "- **Reserve coverage.** The allowance for credit losses against delinquent loans shows how much of the coming loss is already provisioned.",
        "- **Margin and rate sensitivity.** The high ROA depends on loan yields; a rate path and deposit-cost scenario would test it, which this stress test does not.",
        "- **Roll rates.** Movement from 30 to 60 to 90+ days delinquent gives an earlier signal than charge-offs.",
        "",
        "## Caveats",
        "",
        "Balances and the net worth ratio are as filed with NCUA; other ratios are derived with Financial Performance "
        "Report conventions and can differ slightly from NCUA's own. The stress test is illustrative capital arithmetic, "
        "not a supervisory stress test, and does not model risk-based capital or interest-rate risk. CU Pulse is not "
        "affiliated with NCUA or Navy Federal.",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
