import { ArrowLeft, Printer } from 'lucide-react'
import { FanChart, FanLegend } from '../components/Charts.jsx'
import { Skeleton } from '../components/Chrome.jsx'
import { fanSeries, latest, latestPeer } from '../lib/analysis.js'
import { count, fmt, isNum, ordinal, pct, quarter, usd } from '../lib/format.js'
import { href } from '../lib/router.js'
import { BalanceTable, Reading } from './Overview.jsx'

/** One printable page: the read-out an analyst would drop into a board packet. */
export default function Report({ inst, peers, fc, meta }) {
  const now = latest(inst)
  const from = `${Number(inst.latest_quarter.slice(0, 4)) - 4}${inst.latest_quarter.slice(4)}`
  const ready = peers && fc

  return (
    <div className="report">
      <div className="report-actions no-print">
        <a className="button" href={href(inst.cu_number)}>
          <ArrowLeft size={14} strokeWidth={2} /> Back to dashboard
        </a>
        <button type="button" className="button primary" onClick={() => window.print()} disabled={!ready}>
          <Printer size={14} strokeWidth={2} /> Print or save as PDF
        </button>
      </div>

      <article className="sheet">
        <header className="sheet-head">
          <div>
            <h1>{inst.name}</h1>
            <p className="sheet-facts">
              Charter {inst.cu_number} · {inst.city}, {inst.state} · {inst.charter_type} · {usd(now.total_assets)} assets ·{' '}
              {count(now.members)} members{isNum(inst.asset_rank) ? ` · #${inst.asset_rank} of ${count(inst.active_count)} by assets` : ''}
            </p>
          </div>
          <div className="sheet-mark">
            <b>CU Pulse</b>
            <span>Read-out, {quarter(inst.latest_quarter)}</span>
          </div>
        </header>

        <table className="data sheet-vitals">
          <thead>
            <tr>
              <th scope="col">Metric</th>
              <th scope="col">{quarter(inst.latest_quarter)}</th>
              <th scope="col">Year ago</th>
              <th scope="col">Peer median</th>
              <th scope="col">Percentile</th>
            </tr>
          </thead>
          <tbody>
            {[...meta.headline, 'net_charge_off_rate', 'loan_to_share'].map((k) => {
              const p = latestPeer(peers, k)
              const yr = inst.quarters[inst.quarters.length - 5]
              const f = k.includes('growth') || k === 'loan_to_share' ? (v) => pct(v, 1) : (v) => pct(v)
              return (
                <tr key={k}>
                  <th scope="row" style={{ fontWeight: 600 }}>{meta.definitions[k].label}</th>
                  <td>{f(now[k])}</td>
                  <td className="muted">{f(yr?.[k])}</td>
                  <td>{f(p?.median)}</td>
                  <td>{isNum(p?.percentile) ? ordinal(p.percentile) : '—'}</td>
                </tr>
              )
            })}
          </tbody>
        </table>

        <div className="sheet-row">
          <section>
            <h2>Net worth ratio, reported and projected</h2>
            {fc ? (
              <FanChart rows={fanSeries(inst, fc.series.net_worth_ratio, 'net_worth_ratio', from)} format={fmt.pct} zones height={210} reveal={false} label="Net worth ratio" />
            ) : (
              <Skeleton height={210} />
            )}
            <FanLegend zones />
          </section>
          <section>
            <h2>Total assets, reported and projected</h2>
            {fc ? (
              <FanChart rows={fanSeries(inst, fc.series.total_assets, 'total_assets', from)} format={fmt.usd} height={210} reveal={false} label="Total assets" />
            ) : (
              <Skeleton height={210} />
            )}
          </section>
        </div>

        <section>
          <h2>Reading</h2>
          {ready ? <Reading inst={inst} peers={peers} fc={fc} /> : <Skeleton height={160} />}
        </section>

        <section>
          <h2>Selected balances</h2>
          <BalanceTable inst={inst} quarters={5} />
        </section>

        <footer className="sheet-foot">
          Source: NCUA 5300 Call Report quarterly data, {quarter(meta.first_quarter)}–{quarter(meta.latest_quarter)}. Peers:{' '}
          {peers?.method}. Projections are statistical (selected by 8-origin backtest) and shown with 50/80/95% ranges; they are
          not guidance. Generated by CU Pulse.
        </footer>
      </article>
    </div>
  )
}
